FROM ruby:3.3-slim

RUN apt-get update && \
    apt-get install -y build-essential git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /site

EXPOSE 4000 35729

CMD bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload --config _config.yml,_config_dev.yml
